name: Build and deploy ecommerce
on:
    push:
        branches:
            - main
jobs:
    build-deploy:
        runs-on: ubuntu-latest
        
        steps:
        - name: checkout code
          uses: actions/checkout@v3

        - name: setup node js
          uses: actions/setup-node@v3
          with:
            node-version: 18

        - name: Install dependencies
          run: npm install

        - name: Build react app
          run: npm run dist
          
        - name: List files 
          run: ls -al && ls -al dist

        # - name: AWS CREDENTIALS
        #   uses: aws-actions/configure-aws-credentials@v4
        #   with:
        #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #     aws-region: us-east-1

        # - name: deploy static website on s3
        #   run: aws s3 sync build s3://productapplicationfrontend --delete
          